apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  # labels:
  #   app.kubernetes.io/name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
        - name: app
          image: docker.io/library/app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_host
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_port
            - name: PGUSERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_usr
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  # PostgreSQL default database is the same as the default user
                  key: db_usr
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: passwd
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31000
