apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  # labels:
  #   app.kubernetes.io/name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db
    spec:
      containers:
        - name: db
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_usr
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: passwd
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app.kubernetes.io/name: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
